version: '3'
services:
  banka:
    image: naoufal450/corda-poc:0.1
    volumes:
      - C:/certificates:/opt/corda/certificates # Cetificates folder (from build/nodes/<node-name>/certificates)
      - C:/config:/etc/corda # config folder contains node.conf file (from build/nodes/<node-name>/node.conf)
      - C:/network-parameters:/opt/corda/network-parameters # File from build/nodes/<node-name>/network-parameters
      - C:/additional-node-infos:/opt/corda/additional-node-infos # Folder from build/nodes/<node-name>/additional-node-infos
    ports:
      - "22022:22022"
      - "10003:10003"